// Aluno: Lemersom Fernandes Filho    RA: 2410176
// ADS - 2022/1 - POO - Projeto Final

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class JanelaBat extends javax.swing.JFrame {

    public Bateria bat;
    private static GerBateria gerBat = new GerBateria();
    
    private static JanelaBat janelaBat1;
    
    /**
     * Creates new form JanelaBat
     */
    public JanelaBat() {
        initComponents();
    }
    
    public static JanelaBat getJanelaBat(){
        if(janelaBat1 == null){
            janelaBat1 = new JanelaBat();
        }
        return janelaBat1;
    }
    
    public static GerBateria getGerBat(){
        return gerBat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarca = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblQtdCaixa = new javax.swing.JLabel();
        btCad = new javax.swing.JButton();
        lblQtdBulbo = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        lblQtdTons = new javax.swing.JLabel();
        btConsultar = new javax.swing.JButton();
        lblPreco = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabBat = new javax.swing.JTable();
        txtQtdCaixa = new javax.swing.JTextField();
        lblBateria = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtQtdBulbo = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        txtQtdTons = new javax.swing.JTextField();
        lblQtdSurdo = new javax.swing.JLabel();
        txtQtdSurdo = new javax.swing.JTextField();
        txtQtdChimbal = new javax.swing.JTextField();
        lblQtdChimbal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Janela Bateria");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMarca.setText("Marca:");

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblQtdCaixa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQtdCaixa.setText("Quantidade de Caixas:");

        btCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCad.setText("Cadastrar");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });

        lblQtdBulbo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQtdBulbo.setText("Quantidade de Bulbos:");

        btAlterar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        lblQtdTons.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQtdTons.setText("Quantidade de Tons:");

        btConsultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPreco.setText("Preço:");

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        txtTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tabBat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Marca", "QtdCaixa", "QtdBulbo", "QtdTons", "QtdSurdo", "QtdChimbal", "Preco"
            }
        ));
        jScrollPane1.setViewportView(tabBat);

        txtQtdCaixa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblBateria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBateria.setText("Bateria");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCodigo.setText("Codigo do Item:");

        txtQtdBulbo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipo.setText("Tipo: ");

        txtQtdTons.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblQtdSurdo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQtdSurdo.setText("Quantidade de Surdos:");

        txtQtdSurdo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtQtdChimbal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblQtdChimbal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQtdChimbal.setText("Quantidade de Chimbal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCad)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btAlterar)))
                        .addGap(103, 103, 103)
                        .addComponent(btExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(74, 74, 74)
                .addComponent(btSair)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMarca)
                                .addGap(28, 28, 28)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdCaixa)
                                .addGap(28, 28, 28)
                                .addComponent(txtQtdCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdBulbo)
                                .addGap(28, 28, 28)
                                .addComponent(txtQtdBulbo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdTons)
                                .addGap(28, 28, 28)
                                .addComponent(txtQtdTons, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdSurdo)
                                .addGap(28, 28, 28)
                                .addComponent(txtQtdSurdo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPreco)
                                .addGap(28, 28, 28)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdChimbal)
                                .addGap(28, 28, 28)
                                .addComponent(txtQtdChimbal, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(28, 28, 28)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addGap(28, 28, 28)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lblBateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdCaixa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdBulbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdBulbo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdTons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdTons))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdSurdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdSurdo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdChimbal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdChimbal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLimpar)
                            .addComponent(btSair))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCad)
                            .addComponent(btConsultar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btExcluir)
                            .addComponent(btAlterar))
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        cadastrar();
        listarTab();
    }//GEN-LAST:event_btCadActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterar();
        listarTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
        listarTab();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    public void excluir(){
        bat = new Bateria();
        
        bat.setCodigo(txtCodigo.getText());
        
        bat = gerBat.consultaCodigo(bat);
        
        if(bat != null){
            
            txtCodigo.setText(bat.getCodigo());
            txtTipo.setText(bat.getTipo());
            txtMarca.setText(bat.getMarca());
            txtQtdCaixa.setText(Integer.toString(bat.getQtdCaixa()));
            txtQtdBulbo.setText(Integer.toString(bat.getQtdBulbo()));
            txtQtdTons.setText(Integer.toString(bat.getQtdTons()));
            txtQtdSurdo.setText(Integer.toString(bat.getQtdSurdo()));
            txtQtdChimbal.setText(Integer.toString(bat.getQtdChimbal()));
            txtPreco.setText(Integer.toString(bat.getVenda1().getPreco()));
            

            int perg = JOptionPane.showConfirmDialog(null, "Deseja excluir?", 
                                   "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);
            if(perg == 0){
                gerBat.excluirBat(bat);
                JOptionPane.showMessageDialog(null, "Sucesso na exclusão", "Exclusão", 1);
                
            }
            
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Bateria não cadastrada", "Erro na Consulta", 0);
            limpar();
        }
    }
    
    public void alterar(){
        bat = new Bateria();
        
        bat.setCodigo(txtCodigo.getText());
        
        bat = gerBat.alteraBat(bat);
        
        if(bat != null){
            txtCodigo.setText(bat.getCodigo());
            txtTipo.setText(bat.getTipo());
            txtMarca.setText(bat.getMarca());
            txtQtdCaixa.setText(Integer.toString(bat.getQtdCaixa()));
            txtQtdBulbo.setText(Integer.toString(bat.getQtdBulbo()));
            txtQtdTons.setText(Integer.toString(bat.getQtdTons()));
            txtQtdSurdo.setText(Integer.toString(bat.getQtdSurdo()));
            txtQtdChimbal.setText(Integer.toString(bat.getQtdChimbal()));
            txtPreco.setText(Integer.toString(bat.getVenda1().getPreco()));
            JOptionPane.showMessageDialog(null, "Sucesso na alteração de dados", "Alteração", 1);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Bateria não cadastrada", "Erro na Consulta", 0);
            limpar();
        }
    }
    
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabBat.getModel();
        int i = 0;
        
        modelo.setRowCount(i);
        
        for(Bateria bat : gerBat.getBdBat()){
            modelo.insertRow(i, new Object[]{bat.getCodigo(), bat.getTipo(), bat.getMarca(), 
                    bat.getQtdCaixa(), bat.getQtdBulbo(), bat.getQtdTons(), bat.getQtdSurdo(),
                    bat.getQtdChimbal(), bat.getVenda1().getPreco()});
            i++;
        }
    }
    
    public void consultar(){
        bat = new Bateria();
        
        bat.setCodigo(txtCodigo.getText());
        
        bat = gerBat.consultaCodigo(bat);
        
        if(bat != null){
            txtCodigo.setText(bat.getCodigo());
            txtTipo.setText(bat.getTipo());
            txtMarca.setText(bat.getMarca());
            txtQtdCaixa.setText(Integer.toString(bat.getQtdCaixa()));
            txtQtdBulbo.setText(Integer.toString(bat.getQtdBulbo()));
            txtQtdTons.setText(Integer.toString(bat.getQtdTons()));
            txtQtdSurdo.setText(Integer.toString(bat.getQtdSurdo()));
            txtQtdChimbal.setText(Integer.toString(bat.getQtdChimbal()));
            txtPreco.setText(Integer.toString(bat.getVenda1().getPreco()));
            JOptionPane.showMessageDialog(null, "Sucesso na consulta", "Consulta", 1);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Bateria não cadastrada", "Erro na Consulta", 0);
            limpar();
        }
    }
    
    public void cadastrar(){
        bat = new Bateria();
        
        
        bat.setCodigo(txtCodigo.getText());
        bat.setTipo(txtTipo.getText());
        bat.setMarca(txtMarca.getText());
        bat.setQtdCaixa(Integer.parseInt(txtQtdCaixa.getText()));
        bat.setQtdBulbo(Integer.parseInt(txtQtdBulbo.getText()));
        bat.setQtdTons(Integer.parseInt(txtQtdTons.getText()));
        bat.setQtdSurdo(Integer.parseInt(txtQtdSurdo.getText()));
        bat.setQtdChimbal(Integer.parseInt(txtQtdChimbal.getText()));
        bat.getVenda1().setPreco(Integer.parseInt(txtPreco.getText()));
        
                
        bat = gerBat.cadBat(bat);
        
        if(bat != null){
            JOptionPane.showMessageDialog(null, "Bateria cadastrada com sucesso", 
                        "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Bateria já possui cadastro", 
                        "Erro no cadastro", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, 
                "Deseja Sair?", 
                "Sair", 
                JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    public void limpar(){
        txtCodigo.setText("");
        txtTipo.setText("");
        txtMarca.setText("");
        txtQtdCaixa.setText("");
        txtQtdBulbo.setText("");
        txtQtdTons.setText("");
        txtQtdSurdo.setText("");
        txtQtdChimbal.setText("");
        txtPreco.setText("");
        txtCodigo.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaBat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaBat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaBat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaBat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaBat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCad;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBateria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQtdBulbo;
    private javax.swing.JLabel lblQtdCaixa;
    private javax.swing.JLabel lblQtdChimbal;
    private javax.swing.JLabel lblQtdSurdo;
    private javax.swing.JLabel lblQtdTons;
    private javax.swing.JLabel lblTipo;
    private static javax.swing.JTable tabBat;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtdBulbo;
    private javax.swing.JTextField txtQtdCaixa;
    private javax.swing.JTextField txtQtdChimbal;
    private javax.swing.JTextField txtQtdSurdo;
    private javax.swing.JTextField txtQtdTons;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
