// Aluno: Lemersom Fernandes Filho    RA: 2410176
// ADS - 2022/1 - POO - Projeto Final

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstrumentoMusical = new javax.swing.JLabel();
        btGuitarra = new javax.swing.JButton();
        btViolao = new javax.swing.JButton();
        btBateria = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuTabelas = new javax.swing.JMenu();
        MnItemTabGuit = new javax.swing.JMenuItem();
        MnItemTabViolao = new javax.swing.JMenuItem();
        MnItemTabBat = new javax.swing.JMenuItem();
        MnItemTabProd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblInstrumentoMusical.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInstrumentoMusical.setText("Instrumento Músical");

        btGuitarra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btGuitarra.setText("Guitarra");
        btGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuitarraActionPerformed(evt);
            }
        });

        btViolao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btViolao.setText("Violão");
        btViolao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViolaoActionPerformed(evt);
            }
        });

        btBateria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btBateria.setText("Bateria");
        btBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBateriaActionPerformed(evt);
            }
        });

        MenuTabelas.setText("Tabelas");

        MnItemTabGuit.setText("Tabela Guitarra");
        MnItemTabGuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabGuitActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabGuit);

        MnItemTabViolao.setText("Tabela Violão");
        MnItemTabViolao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabViolaoActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabViolao);

        MnItemTabBat.setText("Tabela Bateria");
        MnItemTabBat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabBatActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabBat);

        MnItemTabProd.setText("Tabela Produto");
        MnItemTabProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItemTabProdActionPerformed(evt);
            }
        });
        MenuTabelas.add(MnItemTabProd);

        MenuPrincipal.add(MenuTabelas);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInstrumentoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btViolao, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btGuitarra)
                            .addComponent(btBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(311, 311, 311))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblInstrumentoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btGuitarra)
                .addGap(66, 66, 66)
                .addComponent(btViolao)
                .addGap(62, 62, 62)
                .addComponent(btBateria)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuitarraActionPerformed
        JanelaGuit.getJanelaGuit().setVisible(true);
    }//GEN-LAST:event_btGuitarraActionPerformed

    private void btViolaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViolaoActionPerformed
        JanelaViolao.getJanelaViolao().setVisible(true);
    }//GEN-LAST:event_btViolaoActionPerformed

    private void btBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBateriaActionPerformed
        JanelaBat.getJanelaBat().setVisible(true);
    }//GEN-LAST:event_btBateriaActionPerformed

    private void MnItemTabGuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabGuitActionPerformed
        TabGuit.getTabGuit().setVisible(true);
        TabGuit.listarTab1();
    }//GEN-LAST:event_MnItemTabGuitActionPerformed

    private void MnItemTabViolaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabViolaoActionPerformed
        TabViolao.getTabViolao().setVisible(true);
        TabViolao.listarTab1();
    }//GEN-LAST:event_MnItemTabViolaoActionPerformed

    private void MnItemTabBatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabBatActionPerformed
        TabBat.getTabBat().setVisible(true);
        TabBat.listarTab1();
    }//GEN-LAST:event_MnItemTabBatActionPerformed

    private void MnItemTabProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItemTabProdActionPerformed
        TabProduto.getTabProd().setVisible(true);
        TabProduto.listarTab1();
    }//GEN-LAST:event_MnItemTabProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuTabelas;
    private javax.swing.JMenuItem MnItemTabBat;
    private javax.swing.JMenuItem MnItemTabGuit;
    private javax.swing.JMenuItem MnItemTabProd;
    private javax.swing.JMenuItem MnItemTabViolao;
    private javax.swing.JButton btBateria;
    private javax.swing.JButton btGuitarra;
    private javax.swing.JButton btViolao;
    private javax.swing.JLabel lblInstrumentoMusical;
    // End of variables declaration//GEN-END:variables
}
